# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('image', models.ImageField(height_field='height', upload_to='', validators=[photos.validators.validate_file_extension], width_field='width')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commentary', models.TextField(max_length=300)),
                ('views', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
